variable "ami_ubuntu" {}
variable "instance_type" {}
variable "key_name" {}
variable "ansible-sg" {}
variable "subnet_id" {}
variable "prv_key" {}
variable "HAProxy1_IP" {}
variable "HAProxy2_IP" {}
variable "master1_IP" {}
variable "master2_IP" {}
variable "master3_IP" {}
variable "worker1_IP" {}
variable "worker2_IP" {}
variable "worker3_IP" {}
variable "ansible_server" {}
variable "bastion_host" {}